"""add external_items table

Revision ID: 23b763ad1409
Revises: 4ee8b45b32b4
Create Date: 2026-01-31 17:43:16.694942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b763ad1409'
down_revision: Union[str, Sequence[str], None] = '4ee8b45b32b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock_total', sa.Integer(), nullable=False),
    sa.Column('stock_reserved', sa.Integer(), nullable=False),
    sa.Column('stock_available', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.add_column('external_items', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('external_items', sa.Column('external_item_id', sa.String(), nullable=False))
    op.add_column('external_items', sa.Column('external_sku', sa.String(), nullable=True))
    op.add_column('external_items', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('external_items', sa.Column('status', sa.String(), nullable=True))
    op.add_column('external_items', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.alter_column('external_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_index(op.f('ix_external_items_external_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_import_run_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_sku'), table_name='external_items')
    op.create_index(op.f('ix_external_items_external_item_id'), 'external_items', ['external_item_id'], unique=False)
    op.create_index(op.f('ix_external_items_product_id'), 'external_items', ['product_id'], unique=False)
    op.create_unique_constraint('uq_external_item_channel', 'external_items', ['channel_id', 'external_item_id'])
    op.drop_constraint(None, 'external_items', type_='foreignkey')
    op.drop_constraint(None, 'external_items', type_='foreignkey')
    op.create_foreign_key(None, 'external_items', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'external_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('external_items', 'title')
    op.drop_column('external_items', 'external_id')
    op.drop_column('external_items', 'import_run_id')
    op.drop_column('external_items', 'sku')
    op.create_unique_constraint('uq_ml_auth_channel', 'mercadolibre_auth', ['channel_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_ml_auth_channel', 'mercadolibre_auth', type_='unique')
    op.add_column('external_items', sa.Column('sku', sa.VARCHAR(), nullable=True))
    op.add_column('external_items', sa.Column('import_run_id', sa.INTEGER(), nullable=False))
    op.add_column('external_items', sa.Column('external_id', sa.VARCHAR(), nullable=False))
    op.add_column('external_items', sa.Column('title', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'external_items', type_='foreignkey')
    op.drop_constraint(None, 'external_items', type_='foreignkey')
    op.create_foreign_key(None, 'external_items', 'catalog_import_runs', ['import_run_id'], ['id'])
    op.create_foreign_key(None, 'external_items', 'channels', ['channel_id'], ['id'])
    op.drop_constraint('uq_external_item_channel', 'external_items', type_='unique')
    op.drop_index(op.f('ix_external_items_product_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_external_item_id'), table_name='external_items')
    op.create_index(op.f('ix_external_items_sku'), 'external_items', ['sku'], unique=False)
    op.create_index(op.f('ix_external_items_import_run_id'), 'external_items', ['import_run_id'], unique=False)
    op.create_index(op.f('ix_external_items_id'), 'external_items', ['id'], unique=False)
    op.create_index(op.f('ix_external_items_external_id'), 'external_items', ['external_id'], unique=False)
    op.alter_column('external_items', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
    op.drop_column('external_items', 'updated_at')
    op.drop_column('external_items', 'status')
    op.drop_column('external_items', 'is_active')
    op.drop_column('external_items', 'external_sku')
    op.drop_column('external_items', 'external_item_id')
    op.drop_column('external_items', 'product_id')
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
