"""add mercadolibre oauth auth table

Revision ID: 4ee8b45b32b4
Revises: 91d3c0cb47cc
Create Date: 2026-01-25 23:43:49.879313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ee8b45b32b4'
down_revision: Union[str, Sequence[str], None] = '91d3c0cb47cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
