"""add import run fields

Revision ID: 59848bccb0ff
Revises: e7f60b646543
Create Date: 2026-01-05 22:22:05.893173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59848bccb0ff'
down_revision: Union[str, Sequence[str], None] = 'e7f60b646543'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalog_import_runs', sa.Column('channel_id', sa.Integer(), nullable=False))
    op.add_column('catalog_import_runs', sa.Column('status', sa.String(), nullable=False))
    op.add_column('catalog_import_runs', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'catalog_import_runs', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'catalog_import_runs', type_='foreignkey')
    op.drop_column('catalog_import_runs', 'finished_at')
    op.drop_column('catalog_import_runs', 'status')
    op.drop_column('catalog_import_runs', 'channel_id')
    # ### end Alembic commands ###
