"""add status to sales

Revision ID: 74caf428e2b5
Revises: 907be4cec9f0
Create Date: 2026-02-15 21:32:59.606031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74caf428e2b5'
down_revision: Union[str, Sequence[str], None] = '907be4cec9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.add_column('sales', sa.Column('status', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('ml_last_updated', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('sales', 'external_order_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_sales_external_order_id'), table_name='sales')
    op.create_index(op.f('ix_sales_external_order_id'), 'sales', ['external_order_id'], unique=True)
    op.create_index(op.f('ix_sales_status'), 'sales', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sales_status'), table_name='sales')
    op.drop_index(op.f('ix_sales_external_order_id'), table_name='sales')
    op.create_index(op.f('ix_sales_external_order_id'), 'sales', ['external_order_id'], unique=False)
    op.alter_column('sales', 'external_order_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('sales', 'ml_last_updated')
    op.drop_column('sales', 'status')
   
    # ### end Alembic commands ###
