"""initial schema

Revision ID: 91d3c0cb47cc
Revises: 
Create Date: 2026-01-25 23:43:34.471607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d3c0cb47cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('catalog_import_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mercadolibre_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('ml_user_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id'),
    sa.UniqueConstraint('channel_id', name='uq_ml_auth_channel')
    )
    op.create_index(op.f('ix_mercadolibre_auth_id'), 'mercadolibre_auth', ['id'], unique=False)
    op.create_table('external_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_run_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['import_run_id'], ['catalog_import_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_items_channel_id'), 'external_items', ['channel_id'], unique=False)
    op.create_index(op.f('ix_external_items_external_id'), 'external_items', ['external_id'], unique=False)
    op.create_index(op.f('ix_external_items_id'), 'external_items', ['id'], unique=False)
    op.create_index(op.f('ix_external_items_import_run_id'), 'external_items', ['import_run_id'], unique=False)
    op.create_index(op.f('ix_external_items_sku'), 'external_items', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_items_sku'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_import_run_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_external_id'), table_name='external_items')
    op.drop_index(op.f('ix_external_items_channel_id'), table_name='external_items')
    op.drop_table('external_items')
    op.drop_index(op.f('ix_mercadolibre_auth_id'), table_name='mercadolibre_auth')
    op.drop_table('mercadolibre_auth')
    op.drop_table('catalog_import_runs')
    op.drop_table('channels')
    # ### end Alembic commands ###
